# Utilise une image Python comme base
FROM python:3.9

# Répertoire de travail dans le conteneur
WORKDIR /app

# Copie du code de l'application dans le conteneur
COPY . /app

# Installation des dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Exposer le port utilisé par l'application
EXPOSE 8000

# Commande pour lancer l'application avec Uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
